"""initial_schema

Revision ID: 7cad6041afa2
Revises: 
Create Date: 2026-06-22 16:25:28.853989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cad6041afa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='genderenum'), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('place_of_birth', sa.String(length=200), nullable=True),
    sa.Column('date_of_death', sa.String(length=10), nullable=True),
    sa.Column('place_of_death', sa.String(length=200), nullable=True),
    sa.Column('is_living', sa.Boolean(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('occupations', sa.JSON(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('avatar_media_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media.id'], name='fk_persons_avatar_media_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'document', name='mediatype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_taken', sa.String(length=10), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_person_id'), 'media', ['person_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_a_id', sa.Uuid(), nullable=False),
    sa.Column('person_b_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('parent_child', 'partner', name='relationshiptype'), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('end_reason', sa.Enum('divorce', 'death', 'annulment', name='endreason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_person_a_id'), 'relationships', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_person_b_id'), 'relationships', ['person_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_person_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_media_person_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('persons')
    # ### end Alembic commands ###
